
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  team,
  analytics,
  tabgroup,
}: {
  children: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
  tabgroup: React.ReactNode

}) {
  return (
    <html lang="en">
      <body>
        {children}
        {analytics}
        {team}
        {tabgroup}
      </body>
    </html>
  )
}
